### ISSUE TITLE
hot reload problem

### ISSUE THREAD

**Issue by behindthebeat** [xuyangdong/govern_project#2]
![image](https://user-images.githubusercontent.com/8576839/30784258-b4b3179e-a184-11e7-81ca-32140a2f5ddd.png)

<Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions.

**Comment by xuyangdong** [comment]
这个问题一直有，然后也一直不知道怎么解决，声哥看了说warnning问题也不大就一直在那

**Comment by behindthebeat** [comment]
`store.js` 的 `createMyStore()` 方法，加上下面这段
```javascript
// ...
	if (module.hot) {
	    module.hot.accept('./reducer', () => {
	    	const nextRootReducer = require('./reducer').default;
	    	store.replaceReducer(nextRootReducer);
	    });
	}
// ...
```

然后把 createMyStore 的过程，从 `client.jsx` 移到 `index.js` 里面去
